### ISSUE TITLE
Building the micro ros workspace

### ISSUE THREAD

**Issue by ghost** [micro-ROS/micro-ROS-demos#2]
Hello there,
I stumbled across this project and I'm very interested in testing it. However, the link to the instructions about how to build the micro ros workspace leads to an empty page. Do you have an instruction at hand somewhere?
Thank you and have a nice day!

**Comment by BorjaOuterelo** [comment]
Hi @ToRaVe.

You are right, some of the links are not properly set.
I will update the README.
