### ISSUE TITLE
Repo cleaning

### ISSUE THREAD

**Issue by julionce** [micro-ROS/micro-ROS-demos#21]
The following is a list of suggested actions to clean-up this repo:

- [x] rebase [executor] branch over [crystal] and/or [dashing],
- [x] rebase [pubsub] over [dashing],
- [x] change #19 target branch to [dashing],
- [ ] rebase [parameters] over [dashing],
- [ ] remove branches: [master]
- [ ] remove branches:  [develop]
- [ ] remove branches: [migration]
- [x] remove branches: [configuration].

[master]: https://github.com/micro-ROS/micro-ROS-demos/tree/master
[develop]: https://github.com/micro-ROS/micro-ROS-demos/tree/develop
[crystal]: https://github.com/micro-ROS/micro-ROS-demos/tree/crystal
[executor]: https://github.com/micro-ROS/micro-ROS-demos/tree/feature/rcl_executor_examples
[configuration]: https://github.com/micro-ROS/micro-ROS-demos/tree/feature/configuration
[migration]: https://github.com/micro-ROS/micro-ROS-demos/tree/feature/dashing_migration
[pubsub]: https://github.com/micro-ROS/micro-ROS-demos/tree/feature/add_pubsub_example
[parameters]: https://github.com/micro-ROS/micro-ROS-demos/tree/feature/parameters

**Comment by ralph-lange** [comment]
The demos on the executor should be now inside the rclc repo. Thus, the executor branch here can be deleted, or @JanStaschulat ?

**Comment by ralph-lange** [comment]
Just talked to @JanStaschulat. Branch deleted.

**Comment by pablogs9** [comment]
Hello, is someone using branches master, develop or dashing migration?
