### ISSUE TITLE
RCL demos in Foxy

### ISSUE THREAD

**Issue by pablogs9** [micro-ROS/micro-ROS-demos#24]
I'm preparing this repository for the Foxy release, and I was wondering what should we do with the RCL folder. 

Maybe if the micro-ROS default client library is RCLC, RCL examples should not exist. But on the other hand, there are interesting examples in RCL folder such as configuration_examples, actions or services.

Should we gradually port this functionality to the RCLC so the RCL folder can be removed?

**Comment by ralph-lange** [comment]
My opinion: It should be ported soon. You may even move the demos from rcl/\* right now to the rclc folder and then include the rclc convenience functions gradually later. By avoiding two folders rcl and rclc, we emphasize that we consider one C API only, namely rcl+rclc. How much a developer uses from rclc in the daily practice is up to him/her. The rclc package is intended to simplify the developer's life - but he/she does not have to.

**Comment by pablogs9** [comment]
Okey, so we move all examples to `rclc` folder. I'm going to do a PR with these changes soon.
