### ISSUE TITLE
Windows builds: any special infrastructure needed?

### ISSUE THREAD

**Issue by gavanderhoorn** [micro-ROS/micro-ROS-demos#54]
More of a question, not an actual issue, but Discussions is not enabled, so here goes.

(if this is an RTFM, please point me to it)

I'd be interested in building the demos on a Windows machine, targetting Windows.

The readme seems to suggest this is possible in [Run demonstration (Windows)](https://github.com/micro-ROS/micro-ROS-demos#run-demonstration-windows), but I don't see this mentioned anywhere else.

The [Previous Step](https://github.com/micro-ROS/micro-ROS-demos/tree/4ab33959122bcb99f31426c519cc6befc97f26a1#previous-step) section links to a [microROS/micro-ROS-doc](https://github.com/microROS/micro-ROS-doc) repository, but that doesn't appear to be around any more.

Could you perhaps give a few hints on what would be needed? I imagine a working Windows-based ROS 2 dev env, but what else?

**Comment by gavanderhoorn** [comment]
@ted-miller: can this be closed?

In the end we did build the Agent on Windows, correct?

**Comment by ted-miller** [comment]
Yes, the agent will build successfully on Windows.
https://github.com/Yaskawa-Global/motoros2#windows
