### ISSUE TITLE
[FEA] add intra-mcu communication example.

### ISSUE THREAD

**Issue by ZhenshengLee** [micro-ROS/micro-ROS-demos#57]
As microxrcedds is a agent-based dds, every node inside/outside mcu will need to exchange info with each other through the agent.

Besides the agent-less solution of embeddedRTPS, there is a PR that can help to do intra-mcu communication, and an example is needed.

Thanks.

Hi @eden-desta! So, @pablogs9 has been working hard on a new _Shared Memory_ feature, about which you can read in [this PR](https://github.com/eProsima/Micro-XRCE-DDS-Client/pull/216). The implementation is complete and only pending to be merged. Basically, now the same Client with two entities matching internally can be aware of it and proceed with the communication without the Agent having to mediate it.

It would be great if you could test it and give us some feedback, also regarding whether this feature addresses your use-case. We are excited to know what you guys think of it! Hopefully, it fits your needs!

_Originally posted by @FranFin in https://github.com/micro-ROS/micro-ROS-Agent/issues/37#issuecomment-823969052_

EDIT:
Glad to see it an offically supported feature. https://micro.ros.org/docs/overview/ROS_2_feature_comparison/
![image](https://user-images.githubusercontent.com/17764118/158505037-19d0eaee-2231-40ab-8f0e-ca5e0e5c6002.png)

**Comment by eden-desta** [comment]
This is awesome! I will definitely give it a test! Thank you all for your efforts!

**Comment by Acuadros95** [comment]
This feature can be enabled on compilation time with the Micro-XRCE-DDS middleware `UCLIENT_PROFILE_SHARED_MEMORY` flag: [detail](
https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/develop/CMakeLists.txt#L68).

Then you can just create a set of pub/sub or service server/client on the same topic and they will communicate internally.

At this moment there is not a tutorial specific doc about this feature, but that may change soon. Stay tuned!
