### ISSUE TITLE
Cannot get values from parameter callback

### ISSUE THREAD

**Issue by scottitran** [micro-ROS/micro-ROS-demos#65]
Hi everyone, 

I am dealing with parameter callback of micro-ROS. My program dont show any issue and I can flash it to my esp32, but I think I cannot get values from the parameter callback. I followed this tutorial: https://github.com/micro-ROS/micro-ROS-demos/blob/galactic/rclc/parameter_server/main.c

Can someone please help me? Thank you in advanced.

**Comment by pablogs9** [comment]
Can you take a look @Acuadros95 ?

**Comment by Acuadros95** [comment]
> but I think I cannot get values from the parameter callback

Hi @scottitran, Could you please elaborate on your issue?
- Fill the repository issue template: [link](https://github.com/micro-ROS/micro-ROS-demos/blob/galactic/.github/ISSUE_TEMPLATE/general-issue.md)
- What is the problem?  How are you setting the parameter values?
- If you are in galactic, check that FastRTPS is being used as ROS2 middleware: 
  `export RMW_IMPLEMENTATION=rmw_fastrtps_cpp`

**Comment by scottitran** [comment]
Hi @Acuadros95, honestly I dont know where is the problem because I don't get any errors when build and flash the program. Besides, when I try to use _ros2 param set_ and I saw the value change by using  _ros2 param get_ but the value in the program not change. Specific here is publish frequency. Below is my code: 
`#include <stdio.h>
#include <unistd.h>
#include <time.h>
#include <string.h>

#include <rcl/rcl.h>
#include <rcl/error_handling.h>
#include <std_msgs/msg/int32.h>
#include <std_msgs/msg/string.h>
#include <std_msgs/msg/float32.h>

#include <tutorial_interfaces/msg/num128b.h>
#include <tutorial_interfaces/msg/num1kb.h>
#include <tutorial_interfaces/msg/num10kb.h>
#include <tutorial_interfaces/msg/num100kb.h>

#include <rclc/rclc.h>
#include <rclc/executor.h>
#include <rclc_parameter/rclc_parameter.h>

#include <driver/gpio.h>

#ifdef ESP_PLATFORM
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#endif

#define RCCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){printf("Failed status on line %d: %d. Aborting.\n",__LINE__,(int)temp_rc);vTaskDelete(NULL);}}
#define RCSOFTCHECK(fn) { rcl_ret_t temp_rc = fn; if((temp_rc != RCL_RET_OK)){printf("Failed status on line %d: %d. Continuing.\n",__LINE__,(int)temp_rc);}}

#define RED_LED 25
// #define GREEN_LED 26

// #define ARRAY_LEN 100
rclc_parameter_server_t param_server;
rcl_timer_t timer;
rcl_publisher_t publisher;
rcl_subscription_t subscriber;

tutorial_interfaces__msg__Num1kb msg_req;
tutorial_interfaces__msg__Num1kb msg_res;

int timer_timeout = 1000;
bool publish = true;

void timer_callback(rcl_timer_t * timer, int64_t last_call_time)
{
	(void)	last_call_time;
	(void)	timer;
	
	// rclc_parameter_set_int(&param_server, "param1", 10);

	if (publish) {

		// msg_req = (int *)calloc(array_size, sizeof(int));
		// for (size_t i =0; i<array_size; i++)
		// 	msg_req.data[i] = rand();
		
		RCSOFTCHECK(rcl_publish(&publisher, &msg_req, NULL));
		// printf("I have publish: \"%s\"\n", msg_req.data[2]);
		gpio_set_level(RED_LED,1);
	}
}

bool on_parameter_changed(const Parameter * old_param, const Parameter * new_param, void * context){
	(void) context;

	if (old_param == NULL && new_param ==NULL){
		return false;
	}

	bool ret = true;
	if (new_param == NULL)
	{
		ret = false;
	}	
	else if	(strcmp(new_param->name.data, "publish_toggle") == 0 && new_param->value.type == RCLC_PARAMETER_BOOL)
		{
			publish = new_param->value.bool_value;
		}	
	else if (strcmp(new_param->name.data, "publish_rate") == 0 && new_param->value.type == RCLC_PARAMETER_INT)
		{
			int64_t old;
			RCSOFTCHECK(rcl_timer_exchange_period(&timer, RCL_MS_TO_NS(new_param->value.integer_value), &old));
		}

	return ret;
}

void subscription_callback(const void * msgin)
{
	const tutorial_interfaces__msg__Num1kb * msg = (const tutorial_interfaces__msg__Num1kb *)msgin;
	gpio_set_level(RED_LED,0);
}

void appMain(void * arg)
{
	gpio_pad_select_gpio(RED_LED);
	gpio_set_direction(RED_LED, GPIO_MODE_OUTPUT);


	gpio_set_level(RED_LED,0);

	rcl_allocator_t allocator = rcl_get_default_allocator();
	rclc_support_t support;

	// create init_options
	RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));

	// create node
	rcl_node_t node;
	RCCHECK(rclc_node_init_default(&node, "ESP32", "", &support));

	// create publisher
	RCCHECK(rclc_publisher_init_best_effort(
		&publisher,
		&node,
		ROSIDL_GET_MSG_TYPE_SUPPORT(tutorial_interfaces, msg, Num1kb),
		"ping_msg"));
		
	// create subscriber
	RCCHECK(rclc_subscription_init_best_effort(
		&subscriber,
		&node,
		ROSIDL_GET_MSG_TYPE_SUPPORT(tutorial_interfaces, msg, Num1kb),
		"pong_msg"));

	// create parameter service
	rclc_parameter_server_init_default(&param_server, &node);

	// create timer,
	RCCHECK(rclc_timer_init_default(
		&timer,
		&support,
		RCL_MS_TO_NS(1000),
		timer_callback));

	// create executor
	rclc_executor_t executor;
	RCCHECK(rclc_executor_init(&executor, &support.context, RCLC_PARAMETER_EXECUTOR_HANDLES_NUMBER + 2, &allocator));
	RCCHECK(rclc_executor_add_parameter_server(&executor, &param_server, on_parameter_changed));
	RCCHECK(rclc_executor_add_timer(&executor, &timer));
	RCCHECK(rclc_executor_add_subscription(&executor, &subscriber, &msg_res, &subscription_callback, ON_NEW_DATA));

	// add parameters
	rclc_add_parameter(&param_server, "publish_toggle", RCLC_PARAMETER_BOOL);
	rclc_add_parameter(&param_server, "publish_rate", RCLC_PARAMETER_INT);

	// add parameters contraints
	// rclc_add_parameter_description(&param_server, "publish_toggle", "publish ON/OF parameter", "");
	// rclc_add_parameter_description(&param_server, "publish_rate", "publish rate parameter", "Unit: miliseconds");

	// set parameters initial values 
	rclc_parameter_set_bool(&param_server, "publish_toggle", true);
	rclc_parameter_set_int(&param_server, "publish_rate", 20);

	int64_t publish_rate;
	bool publish_toggle;

	rclc_parameter_get_bool(&param_server, "publish_toggle", &publish_toggle);
	rclc_parameter_get_int(&param_server, "publish_rate", &publish_rate);

	while(1){
		rclc_executor_spin(&executor);
		// usleep(100000);
	}
	
	// rclc_executor_spin(&executor);
	// free resources
	RCCHECK(rcl_publisher_fini(&publisher, &node));
	RCCHECK(rcl_subscription_fini(&subscriber, &node));
	// RCCHECK(rclc_parameter_server_fini(&param_server, &node));
	RCCHECK(rcl_node_fini(&node));

  	vTaskDelete(NULL);
}`

**Comment by Acuadros95** [comment]
I am going to replicate this, need some details:
- Which micro-ROS build system are you using to build and flash? (Including branch)
- What are the exact `ros2 param set` and `ros2 param get` commands you are using
- Whats inside `tutorial_interfaces__msg__Num1kb`? Did you tests this with a regular `std_msgs__msg__Int32`?
- Whats your ROS2 distro?
