### ISSUE TITLE
Porting to teensy with platformio

### ISSUE THREAD

**Issue by usaotearoa** [micro-ROS/micro-ROS-demos#68]
Can you please explain how any of these examples can be ported to teensy in platformio?
Also it needs to be using serial communication.

Thanks.

**Comment by usaotearoa** [comment]
Another question is,
Do I need to do anything in terms of FreeRTOS, when going the approach of using micro-ROS with the teensy under platformio on Ubuntu? Or is this all handled in the background?

**Comment by pablogs9** [comment]
Duplicated https://github.com/micro-ROS/micro_ros_platformio/issues/66
