### ISSUE TITLE
demo for publishing diagnostic status message

### ISSUE THREAD

**Issue by patrickwasp** [micro-ROS/micro-ROS-demos#70]
Can we get a demo for publishing a diagnostic message with a key value sequence? 

I'm not sure how to allocate, initialize, and assign `diagnostic_msgs/msg/KeyValue[] values`

https://docs.ros2.org/foxy/api/diagnostic_msgs/msg/DiagnosticStatus.html

**Comment by pablogs9** [comment]
Hello @patrickwasp, here you have documentation on how to init memory for types in micro-ROS: https://docs.vulcanexus.org/en/latest/rst/tutorials/micro/memory_management/memory_management.html#message-memory
